### ISSUE TITLE
What does Autopause do?

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#13]
1. What does "1.8 km/h -3" mean?
2. When is Autopause applied? During recording or during postprocessing? The latter would make sense to me, but a quick test did not confirm that.
3. Btw, if the App is in German, it should be "1,8 km/h ...". And "Distance filter" -> "Distanzfilter" or even better something explaining the meaning.

**Comment by Heineken** [comment]
I see that there are some non-trivial options, so you might consider adding question mark buttons that show an explaining text.

**Comment by bailuk** [comment]
1. The first number is the speed that triggers autopause and the second number the count of GPS samples in a row. In this example: switch to pause when there are 3 GPS samples (usually 3 seconds) in a row with no more speed than 1,8 km/h. 
2. The tracker will get paused and resumed according to the above mentioned settings.
3. I've fixed the dot instead of comma issue.

**Comment by Heineken** [comment]
1. IMHO that needs explanation. I might have understood if it had been written as "<1.8 km/h for 3s"
2. Ah, I understood once I used it. I will comment in https://github.com/bailuk/AAT/issues/9

**Comment by Heineken** [comment]
I suggest changing the label for the times displayed: "Time" -> "Total time", "Time (Autopause)" -> "Time (without pauses)".

**Comment by bailuk** [comment]
> I suggest changing the label for the times displayed: "Time" -> "Total time", "Time (Autopause)" -> "Time (without pauses)".

I've changed it. But now it looks bad inside the cockpit view. 
Also take a look at my short introduction to string resources here #22 .

**Comment by bailuk** [comment]
Discussion on auto-pause is now  #84
