### ISSUE TITLE
GPS still active after stopping the tracking

### ISSUE THREAD

**Issue by koug44** [bailuk/AAT#2]
Hello,

I've installed v0.9-alpha of your app via F-Droid. For an alpha, I'm pretty happy about it. It does what I want it to do :)

Unfortunatly, sometimes, after I've explicitly stopped the tracking with the «Stop» button and leave the application (at least, put it in the background), the GPS is still on, dragging down my battery.

I've to kill the application to stop it. I'm using a Samsung Galaxy S3 with Android 4.4.2

Thanks

**Comment by bailuk** [comment]
- AAT allocates GPS on startup and releases it when it gets unloaded. This is because the GPS chip needs some time to get the first location fix. And you want GPS to be ready when you need it (for tracking and the map view as well). 

- When not tracking you should always be able to close AAT with the back button (most bottom right button on phone). This will unload the app entirely and will release GPS.

- Now the actual issue: AAT cheats a little with Androids internal app logic. It is been kept in memory as long as possible, when you just put it in background (middle button). I will clean this up in one of the next releases.

**Comment by koug44** [comment]
Thanks: Looking forward to the next release then.
If you need test or feedback, I'll be glad to help

**Comment by bailuk** [comment]
With the latest release AAT will now free GPS after 30 seconds when put in background. There is also an option to lock GPS manually (tap the GPS status area to lock / unlock).
