### ISSUE TITLE
Add introduction

### ISSUE THREAD

**Issue by natrius** [bailuk/AAT#22]
Hello, 

Tbh, i have no clue how this app works or what the arrows do. I'm usally not that helpless but this is not intuitive at all. or something is wrong. 

I started tracking, waited for the GPS-lock and was cycling, finished it with stop and now i can review my last ride. What i experienced:

General:
- On the right top "Tracker" i can start tracking and pause it. I cannot stop it, for example via longpressing.

Menu: 
- Start/Stop, Pause, change the card-style, choose overlays (4 squares with 0 behind?), a nominatim search (i suppose thats the simple navigation tool - not tested) and display settings.

Arrows:
- Right arrow in overview does show stats of the last ride (well, not now anymore for some reason *shrug*).

- Arrow down changes from overview to a card(last ride?)
- From the second arrow down card the arrow right shows the last ride with the stats on bottom. 
- Fullscreen card - there is no right arrow. 

- another tap the down arrow brings me to another card (only difference is fullscreen?)

- and another one brings me back to the overview. 

But HOW do i review my last rides? No clue at all. I'm using a OnePlus3 with LineageOS15.1 (Android 8.1) and if needed i can provide logcat and/or screenshots. Or i'm just missing something crucial :dagger: 

Greets

**Comment by bailuk** [comment]
> Tbh, i have no clue how this app works or what the arrows do. I'm usally not that helpless but this is not intuitive at all. or something is wrong.

I agree that the UI design of AAT is definitely not state of the art. The UI is optimized for outdoor use (it should be usable _while_ cycling for example). This means: big buttons, no sliding or swiping elements, high contrast, whole screen is used for relevant information, etc. And of course it reflects my personal taste for UI design.

> I started tracking, waited for the GPS-lock and was cycling, finished it with stop and now i can review my last ride. What i experienced:
>
> General:
>
>    On the right top "Tracker" i can start tracking and pause it. I cannot stop it, for example via longpressing.

Long pressing is used for Tool-tips on some buttons (try it out for example in the map view). **Stop** is "hidden" inside the main menu because it is only used once during an activity and to prevent the user from accidentally stopping the tracker.

> Menu:
>
>    Start/Stop, Pause, change the card-style, 
>  choose overlays (4 squares with 0 behind?)

There are 4 slots for GPX overlays for the map view(s). You have to select a file first (see further down in this comment).

> , a nominatim search (i suppose thats the simple navigation tool - not tested) and display settings.

"Map search" (I think it says so in newer versions of AAT).


>Arrows:
>
>    Right arrow in overview does show stats of the last ride (well, not now anymore for some reason shrug).

Because you have pressed stop, recording has been finished.

>
>    Arrow down changes from overview to a card(last ride?)
>
>    From the second arrow down card the arrow right shows the last ride with the stats on bottom.

Current ride.

>
>    Fullscreen card - there is no right arrow.

This view has only one page.

>
>    another tap the down arrow brings me to another card (only difference is fullscreen?)

Cockpit A

>
>    and another one brings me back to the overview.

Cockpit B


>But HOW do i review my last rides? No clue at all. I'm using a OnePlus3 with LineageOS15.1 (Android 8.1) and if needed i can provide logcat and/or screenshots. >Or i'm just missing something crucial dagger

## Main view
When starting AAT the first time it shows the **main view**. That's basically a list of sub-views you can open. The first 3 entries are **"Copckpit A, Cockpit B, and Map"** if you have one of these open you can cycle through them with the down arrow. The right arrow switches trough the different pages of the view you are in.

## Map view (or full screen map)
In the **map view** the down arrow is in the main bar (tap the top area of the map). For zooming and navigating tap the bottom area of the map. For grid, search overpass etc. tap  the right area of the map. For the draft editor tap the left side of the map. 
The track that gets currently recorded is always displayed on the map.

## Display recorded track
Now once you have stopped the tracker go back to the **main view** with your phones back button (I really hope that this button is still standard on all Android phones). Then select **Track list** to show a list of all recorded GPX tracks. Every track has a preview image if you tap on this image you'll get a context menu for this GPX-file. _Here you can for example select this track for one of the 4 overlay slots._ You can display any recorded track by taping the text area of the list entry. (Always go back to the list with the phones back button). In the track view there are again different pages (graph, summary and map) and you can cycle trough all tracks with the up and down arrow.

Now to make things even more complicated there are different pages in the **Track list** view (Access them with < ... > ). This pages offer _a map as an alternative to the track list, summary information and filter options_.

**Comment by natrius** [comment]
I have to admin i found it out yesterday night, when just pressing back and seeing it like "wait a second... Oh damn!" Sorry, i somehow managed NOT to simply press "back" the whole time. With the **main view** everything is clear. 
As said, in one Cockpit, the subpages are somehow clear. Somehow i would wish that it would show as tab on top and swiping would switch between the tabs, but at least the swiping would be bad - looking at what you mentioned by not accidentaly changing something.

So, everything clear now, i mayb suggest something:
1, plant the text above in the readme here on github. Its a good explanation.
2, i don't know how complicated it is, but if possible a shortened version on a screen at the first app-start, with extended in settings or a link to the readme here?
3, add one option in the settings menu (three bars left top corner) "Main view" for the retarded like me. With the explanation its maybe not needed.

After some problems on my side, nice app, thanks!
I can provide translations, if needed. Maybe add a section in the readme on how to do that too. :)

Greetings

**Comment by bailuk** [comment]
> 1, plant the text above in the readme here on github. Its a good explanation. 

It's in a separate file now and there's a link in the [README](https://github.com/bailuk/AAT/blob/master/README.md)

> 2, i don't know how complicated it is, but if possible a shortened version on a screen at the first app-start, with extended in settings or a link to the readme here?

I've also put all documentation ([README.md](https://github.com/bailuk/AAT/blob/master/README.md), [README.enduser.md](https://github.com/bailuk/AAT/blob/master/README.enduser.md) and [README.gettingstarted.md](https://github.com/bailuk/AAT/blob/master/README.gettingstarted.md)) inside the app. Just tab **Info /README** in the main view to show all documentation. It's probably still a bit hidden. Do you have a suggestion for a short intro text?

**Comment by bailuk** [comment]
# Regarding translation

## File tree structure
Resources (like text and icons) are located in [app/src/main/res](https://github.com/bailuk/AAT/tree/master/app/src/main/res). 

English text strings are in this file: [/app/src/main/res/values/strings.xml](https://github.com/bailuk/AAT/blob/master/app/src/main/res/values/strings.xml)

German translations are in this file: [/app/src/main/res/values-de/strings.xml](https://github.com/bailuk/AAT/blob/master/app/src/main/res/values-de/strings.xml)

## Modify

- To add a new language just add a `value-<language code>` directory containing a `strings.xml` file.
- Use the English (original) strings.xml as a template.
- Use the same structure (order) as in the original file
- You don't have to translate everything. Just remove an entry and English is used as a fall back.
- You can modify existing strings.
- You can add new suggestions for strings.
- If a **°** gets displayed somewhere inside the app it means the string is not yet in the resource file (only in java code). See [app/src/main/java/ch/bailu/aat/util/ToDo.java](https://github.com/bailuk/AAT/blob/master/app/src/main/java/ch/bailu/aat/util/ToDo.java)

## Contribute

All contribution is welcome. You can open a pull request or send me your translation as e-mail or publish them here as an issue report.

**Comment by natrius** [comment]
What do you mean about the Intro text? For Info, its nice as it is like now imho. For getting started, maybe something like that would be a bit better, don't know if you like it:

When starting AAT for the first time, it shows the **main view**. The first 3 entries are **Cockpit A**, **Cockpit B** and **Map**. It is possible to cycle through this views with the down arrow. **Cockpit A** and **Cockpit B** contains several pages which are possible to access with the right arrow. To get back to the **main view**, simply press back on your cellphone. 

Readme is fine too, imho.  "Translation" part is missing somehow or i'm again blind :D
Or do you mean a short text for an small introduction? Otherwise this issue could be closed, i think.
