### ISSUE TITLE
Galaxy S9 not working

### ISSUE THREAD

**Issue by sugoiuguu** [bailuk/AAT#43]
Hi, the tracker does start, but time doesn't start counting and nothing occurs... Using version 1.15 from F-Droid.

**Comment by bailuk** [comment]
Does your current location gets displayed correctly with a small orange circle inside the map view?

**Comment by sugoiuguu** [comment]
Hey, the GPS sometimes shows 3 dots, most of the time it's apparently detected as being turned off. https://u.sicp.me/bCjfP.jpg

**Comment by bailuk** [comment]
Hi,
The tracker will start counting as soon it receives a GPS signal - not before. If it looses the signal later it will show two time values: one for the actual recorded track so far (related to the last received GPX fix) and a total time related to current system time.

In this case the tracker didn't receive any GPS fixes because you turned off GPS globally.

I assume things work now as expected so I'm gonna close this issue.
