### ISSUE TITLE
how to use offline maps/very old device

### ISSUE THREAD

**Issue by freecycler** [bailuk/AAT#65]
Part of my problem may be that my device is very old: Huawei Ideos U8150-B running FroYo and very little RAM. Because of FroYo I am stuck using old version 1.5beta rather than the current one that needs Ice Cream Sandwich.

I find frequent crashes when trying to view maps. Some tiles get downloaded but not reliably, and some of these turn out to be corrupted or even size 0 bytes. There seem to be somewhat fewer crashes if I only view a map area with tiles that are already downloaded, so I thought why not download a set of maps beforehand as the readme suggests.

I got the smallest useful map for my area from Mapsforge, (v5 if that matters - should I have tried v3?), made a folder maps (which did not exist, I had to create it under cache/tiles), with a subfolder Mapsforge, and put the massachusetts.map and massachusetts.poi in that folder. But the app continues to (sometimes try to) download tiles for this area, most often crashing when it does this.

Also there is the bit in the readme about 
> 4. Disable Mapnik and enable Mapsforge in Menu->Map.

but Mapsforge is not in the menu, how do I do this?

Did this old version support external maps at all, or does that feature only come with newer releases? Where exactly should these files be placed?

**Comment by bailuk** [comment]
Mapsforge depends on API 10. [Changed here in 2017](https://github.com/bailuk/AAT/commit/814c683ab26d54d27a51278147ded4c87d1b2ed6#diff-39e7d8c00954e920b98e7636f0ac30b2).

So you're doomed to use the last version, that doesn't support Mapsforge which is 1.5beta.

The reason why map view does not work could be lack of memory on this old device. 

One work around you can try is to download map tiles with another app that supports OSM tiles and configure AAT so that it shares the tiles directory with this app. Or copy tiles from another device to your phone.

**Comment by bailuk** [comment]
I close this because this issue is old and probably not resolvable. If there is really interest in running AAT on very old devices, please open a new issue.
