### ISSUE TITLE
Application crashes, after adding Cycplus S1 BLE sensor

### ISSUE THREAD

**Issue by tekaeren** [bailuk/AAT#71]
Latest v1.16.1 AAT, works just fine with GPS signal only.
After scanning and once enabling BLE Cycplus S1 Sensor, just after Cockpit display is enabled application crashes - stacktrace sould already hit projects email address.
The behavior persists after restarting the app - even when no sensor is chosen, enabled or connected.

To fix issue application cache and configuration must be cleaned from Android level.

**Comment by bailuk** [comment]
I read the stacktrace you sent me. This crash has nothing to do with Bluetooth.

You have configured AAT to have "aat_data" on a SAF directory. 
When accessing a file in this directory (in this case draft.gpx) IllegalArgumentException gets thrown. Probably AAT has no permission to access its files.

With the latest patch the GPX file loader now catches more exceptions so it will just not load files instead of crash.

**Comment by bailuk** [comment]
I assume this is resolved.
