### ISSUE TITLE
Apptracking - issue during using on Xiaomi Device

### ISSUE THREAD

**Issue by Maligola** [bailuk/AAT#97]
Hello, unfortunately I have massive problems with the app with my new mobile phone. I know that this is not your fault, because it runs on all previous mobile phones without problems.  It's due to the heavily modified OS of Xiaomi.
But maybe you have a solution for me?

Handy: Xiaomi Mi9T
OS: Modified Android 10 by Manufacturer

When the normal tracking process has started and the active GPS signal is displayed, I usually --> turn off the display<---.
From this moment on the phone unfortunately doesn't track anymore.

So if the Display ist always on, tracking works.

So far I have looked at everything in the settings.

Battery settings: 
Allow background usage --ok.
Restrict background usage disabled -- ok
App-> Battery Optimization - deactivated

You got any more ideas? I would like to continue using the program, which unfortunately is not possible mometanously.

Oh yes, the complete system runs behind AFwall - Firewall with minimal network permissions.

THx al lot.

**Comment by bailuk** [comment]
Android 10 has a new security setting for apps that access GPS from the background.
What happens if you set this to "Allow all the time"?
It's in `app info->permissions->location permission`

![Screenshot_1586776395](https://user-images.githubusercontent.com/16067257/79116891-e984af80-7d89-11ea-8072-7278323ea74b.png)

**Comment by bailuk** [comment]
This should be fixed with the latest release. If not you can re-open this issue.
